repos:

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=79]

  - repo: https://github.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-print]
        args: ["--extend-ignore=E203,E402,E203,E501,E122"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=8000"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.42"
    hooks:
      - id: check-manifest
        stages: [manual]
